services:
  mark-board:
    image: mark-board:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
      - '2222:22'
    environment:
      - VITE_BASE=/
    volumes:
      - mark-board-data:/app/kanban-data
      - mark-board-ssh:/root/.ssh
      # Uncomment the line below to mount your SSH public key (replace with your actual path)
      # - ~/.ssh/id_ed25519.pub:/root/.ssh/authorized_keys:ro

volumes:
  mark-board-data:
    driver: local
  mark-board-ssh:
    driver: local
